### ISSUE TITLE
Crash on serving an HDD root directory on Windows

### ISSUE THREAD

**Issue by seangenabe** [zeit/serve#147]
CLI crashes when attempting to serve the root of a drive. I think node is trying to stat System Volume Information which it can't as it's a system directory.

```
Error: EPERM: operation not permitted, stat 'H:\System Volume Information'
_http_outgoing.js:371
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at SendStream.error (C:\Users\Sean\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:301:7)
    at SendStream.onStatError (C:\Users\Sean\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:433:12)
    at onstat (C:\Users\Sean\AppData\Roaming\npm\node_modules\serve\node_modules\send\index.js:734:26)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by leo** [comment]
Might be the same as https://github.com/zeit/serve/issues/145
