### ISSUE TITLE
The serve down off every times

### ISSUE THREAD

**Issue by clonalejandro** [zeit/serve#332]
<h1>The serve down off every times</h1>
<h3>Resume</h3>
<p>I have an vps.<br>
I created a server from my <a href="https://github.com/clonalejandro/webInReact" target=_blank>react project</a> hosted in <a href="https://clonalejandro.me" target=_blank>this web</a><br>
But it's down off every so often and it leaves me with this errors...</p>

<h3>Error</h3>

```
v8::Utils::ReportOOMFailure(char const*, bool) [node]
4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 0xad4b1b [node]
 v8::internal::MarkCompactCollector::Evacuate() [node]
 v8::internal::MarkCompactCollector::CollectGarbage() [node]
 v8::internal::Heap::MarkCompact() [node]
 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 0xe7b618 [node]
 v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [node]
 v8::internal::IncrementalMarkingJob::Task::RunInternal() [node]
 v8::internal::CancelableTask::Run() [node]
 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
 0x1418ceb [node]
 0x142abd8 [node]
 uv_run [node]
 node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [node]
 node::Start(int, char**) [node]
__libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
0x89c371 [node]
at process._tickCallback (internal/process/next_tick.js:160:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /usr/lib/node_modules/serve/lib/server.js:70:15
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/serve/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/serve/node_modules/bluebird/js/release/generators.js:97:49)
    at /usr/lib/node_modules/serve/node_modules/bluebird/js/release/generators.js:201:15
    at /usr/lib/node_modules/serve/bin/serve.js:71:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/serve/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/serve/node_modules/bluebird/js/release/generators.js:97:49)
    at /usr/lib/node_modules/serve/node_modules/bluebird/js/release/generators.js:201:15
    at Promise.then (/usr/lib/node_modules/serve/node_modules/micro-compress/src/index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

<h3>Extra</h3>
<b> Command that I use: </b><span><code>serve build -p 80</code></span>

**Comment by leo** [comment]
This should now be working with the latest release! 🚀 

All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

Thank you for the effort you've put into this!
