### ISSUE TITLE
serve v6.5.4 has UnhandledPromiseRejectionWarning and exits

### ISSUE THREAD

**Issue by 4cm4k1** [zeit/serve#348]
Uh oh, just got this after the latest update.

- **OS:** macOS 10.12.6
- **Node:** v9.11.1
- **Serve:** v6.5.4

**Output:**
```shell
$ serve
(node:79192) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'latest' of undefined
    at getMostRecent (/Users/a1392382/.config/yarn/global/node_modules/update-check/index.js:131:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:79192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process witha non-zero exit code.
```

**Comment by NKozlov** [comment]
The same problem.
OS: macOS 10.13.3
Node: v9.7.1
Serve: v6.5.4
```
(node:7) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED ***.**.**.**:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
In docker container same problem `node:9.11.1-alpine` .
Serve version 6.5.3 not reproduce this bug.

**Comment by justusromijn** [comment]
I have something related. It seems that node 8 is mandatory after this patch release, however the engines entry in the package.json of this project still says node 6 something and higher. It throws with `promisify is not a function` in node 7. Can anyone confirm?

**Comment by justusromijn** [comment]
Actually, I get a `missing ) after argument list` because of the `async` keyword, which is not supported in node < 8.

**Comment by sebelga** [comment]
Same here. Downgrading to v6.5.3 fixed the problem. Thanks @NKozlov

**Comment by justusromijn** [comment]
I also downgraded, solved the issue.

**Comment by MBThaumatec** [comment]
I also have an issue with v6.5.4
It is occurring to me only in `docker-compose`:
Docker image is based on `node:8.9.1`

```
xxx-client_1        | (node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
xxx-client_1        | (node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
production_xxx-client_1 exited with code 0
```

Serve version 6.5.3 not reproduce this bug.

**Comment by dmmulroy** [comment]
This seems to also exist in v6.5.5

**Comment by ansballard** [comment]
As a workaround for anyone getting registry access errors (https://github.com/zeit/serve/issues/348#issuecomment-387245928, https://github.com/zeit/serve/issues/348#issuecomment-380412000, https://github.com/zeit/serve/issues/348#issuecomment-379861147), if you set `NODE_ENV=production`, serve should skip the update check where it's trying to grab from your currently set npm registry, per [this conditional in bin/serve.js](https://github.com/zeit/serve/blob/master/bin/serve.js#L86).
