### ISSUE TITLE
minor release incompatible with node LTS

### ISSUE THREAD

**Issue by omnidan** [zeit/serve#357]
the latest patch release 6.5.6 breaks all deployments for me (which use node LTS):

```
remote:        > serve -s build/        
remote:        /app/node_modules/serve/bin/serve.js:83        
remote:        detect(port).then(async open => {        
remote:                          ^^^^^        
remote:        SyntaxError: missing ) after argument list        
remote:            at createScript (vm.js:56:10)        
remote:            at Object.runInThisContext (vm.js:97:10)        
remote:            at Module._compile (module.js:549:28)        
remote:            at Object.Module._extensions..js (module.js:586:10)        
remote:            at Module.load (module.js:494:32)        
remote:            at tryModuleLoad (module.js:453:12)        
remote:            at Function.Module._load (module.js:445:3)        
remote:            at Module.runMain (module.js:611:10)        
remote:            at run (bootstrap_node.js:394:7)        
remote:            at startup (bootstrap_node.js:160:9)    
```

the issue seems to be that circle ci is not building for node 6 (LTS) anymore, but now only building for latest nodejs: https://github.com/zeit/serve/commit/3f4116efa513733187a0e37200ac1947b3b1e8e2#diff-1d37e48f9ceff6d8030570cd36286a61R5

**Comment by omnidan** [comment]
I just tested with 6.5.5 and it still doesn't work...

**Comment by omnidan** [comment]
If anyone has the same issue: 6.5.3 still works with node LTS

**Comment by leo** [comment]
Node LTS is 8.11.1, which comes with `async/await` support. I just confirmed it is working on that version.
