### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by karbica** [zeit/serve#359]
I am unable to serve up directories. I used create-react-app, ran a build, and attempted to serve it up.

Ran into this error...

```
(node:22821) UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
(node:22821) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22821) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here are my versions...
```
{ asdf: '0.1.0',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.11.1',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.50',
  zlib: '1.2.11' }
```

I do have a `cafile` set in my `.npmrc` file. Another program, `httpster`, works fine.

I removed the `cafile` setting to no avail.

**Comment by ghuser** [comment]
I have the same issue. I just try to do this: `node_modules/.bin/serve --ignore node_modules`. I use  nexus3 as registry:

my `~/.npmrc` is 
    proxy=http://myproxy:8080/
    https-proxy=http://myproxy:8080/
    registry=http://nexusrepo/nexus3/repository/npmjs-group/
    @myscope:registry=http://nexusrepo/nexus3/repository/npmjs-my-hosted/

**Comment by karbica** [comment]
@Vajidbaba 

```
; cli configs
metrics-registry = "https://artifacts.d.company.com/api/npm/npm-virt"
scope = ""
user-agent = "npm/5.6.0 node/v8.11.1 darwin x64"

; userconfig /Users/karbica/.npmrc
@company:registry = "https://artifacts.d.company.com/api/npm/npm-virt"
always-auth = true
cafile = "/Users/karbica/Documents/companycert.pem"
email = "karbi@company.com"
registry = "https://artifacts.d.company.com/api/npm/npm-virt"
strict-ssl = true

; node bin location = /Users/karbica/.nvm/versions/node/v8.11.1/bin/node
; cwd = /Users/karbica
; HOME = /Users/karbica
```

And here is this...
```
$ npm ls -g --depth=0
/Users/karbica/.nvm/versions/node/v8.11.1/lib
├── lerna@2.11.0
├── npm@5.6.0
└── serve@6.5.6
```

**Comment by leo** [comment]
Closing this now, as this issue is not related to serve, but rather to the way how you're installing it from npm.

Thank you for the effort you've put into this!

Please also read the docs for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).

🙏

**Comment by vajin1125** [comment]
Thanks, but i don't clear
