### ISSUE TITLE
Just updated and got an error

### ISSUE THREAD

**Issue by KipOmaha** [zeit/serve#363]
1. Just updated the serve library and got this error.

```
[root]\AppData\Roaming\npm\node_modules\serve\bin\serve.js:83
detect(port).then(async open => {
                  ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

I uninstalled than installed `npm install serve@6.0.0 -g --save-dev` and was able to get it to run.

**Comment by cotterjd** [comment]
I have this error as well. What version did you update from? Can we just revert back to an old version and it work?

**Comment by KipOmaha** [comment]
try `npm install serve@6.0.0 -g --save-dev` or any other version. I got it working at 6.0.0

**Comment by leo** [comment]
Please update Node.js to a version that supports `async/await` (I think it was added in v6 or v7).
