### ISSUE TITLE
Node version incompatability with version 6.5.7

### ISSUE THREAD

**Issue by hlolli** [zeit/serve#370]
My node version is v9.6.1 which is for sure greater than (or equal to) 7.6.0, as thie error message says when installing via yarn.

```
error serve@6.5.7: The engine "node" is incompatible with this module. Expected version ">=7.6.0".
error An unexpected error occurred: "Found incompatible module".
```

this is solveable with
```
yarn --ignore-engines
```

Otherwise I'm quite clueless what's going on here, if it's some screw up on my side, running on linux NixOs 64bit.

**Comment by hoogw** [comment]
I am running node -v 5.6.0 windows 10 X64.  When install, no error, when run, 
error 
`C:\Users\engcid299\AppData\Roaming\nvm\v5.6.0\node_modules\serve\bin\serve.js:12
const {coroutine} = require('bluebird');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)`

**Comment by hlolli** [comment]
```
$ node -v 
v9.6.1
$ npm -v
5.6.0
```
I'm almost on the newest node....

```
error serve@6.5.8: The engine "node" is incompatible with this module. Expected version ">=7.6.0".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/hlolli/Documents/twlfront/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
````
