### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by mquandalle** [zeit/serve#373]
`serve` v6.5.8 isn't working on some version of Ubuntu:

```
{ Error: Command failed: xsel --clipboard --input
xsel: Can't open display: (null)
: Inappropriate ioctl for device


    at Promise.all.then.arr (/home/hansifer/sites/blog/node_modules/clipboardy/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'xsel: Can\'t open display: (null)\n: Inappropriate ioctl for device\n',
  failed: true,
  signal: null,
  cmd: 'xsel --clipboard --input',
  timedOut: false }
```

This bug was reported here: https://github.com/gatsbyjs/gatsby/issues/5122

**Comment by leo** [comment]
This should be working now!

All thanks to `serve-handler`, as described in the notes for the [new release](https://github.com/zeit/serve/releases/tag/7.0.0).
