### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sulliwane** [zeit/serve#378]
Hi, just upgraded to v7, here is my `server.json`:
```json
{
  "public": "build",
  "rewrites": [{ "source": "/**", "destination": "/index.html" }]
}
```
and here is the error:
```bash
INFO: Discovered configuration in `serve.json`
INFO: Accepting connections at http://localhost:3000
(node:44) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at escapeString (/usr/local/lib/node_modules/serve/node_modules/path-to-regexp/index.js:208:14)
    at tokensToRegExp (/usr/local/lib/node_modules/serve/node_modules/path-to-regexp/index.js:304:19)
    at stringToRegexp (/usr/local/lib/node_modules/serve/node_modules/path-to-regexp/index.js:288:10)
    at pathToRegexp (/usr/local/lib/node_modules/serve/node_modules/path-to-regexp/index.js:370:10)
    at sourceMatches (/usr/local/lib/node_modules/serve/node_modules/serve-handler/src/index.js:31:22)
    at toTarget (/usr/local/lib/node_modules/serve/node_modules/serve-handler/src/index.js:47:18)
    at applyRewrites (/usr/local/lib/node_modules/serve/node_modules/serve-handler/src/index.js:75:18)
    at applyRewrites (/usr/local/lib/node_modules/serve/node_modules/serve-handler/src/index.js:78:11)
    at applyRewrites (/usr/local/lib/node_modules/serve/node_modules/serve-handler/src/index.js:78:11)
(node:44) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It's a CRA single page app, with `index.html` under `/build` folder. I need to rewrite everything to point to `/index.html`. 

Is V7 production ready?

thanks!

**Comment by leo** [comment]
Interesting. Thanks for reporting! I'll look into this first thing tomorrow.

**Comment by leo** [comment]
Whoops - wrong button.
