### ISSUE TITLE
SyntaxError in updateCheck function of serve.js

### ISSUE THREAD

**Issue by abhinavankur3** [zeit/serve#435]
/usr/local/lib/node_modules/serve/bin/serve.js:32
const updateCheck = async isDebugging => {
                          ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by compulim** [comment]
Looks like your Node.js is too old to support `const` and `async`.

**Comment by abhinavankur3** [comment]
Yeah I just figured it. Thanks Btw @compulim
