### ISSUE TITLE
I can't call API has HTTPS

### ISSUE THREAD

**Issue by AhmedRedaGitHub** [zeit/serve#560]
when i call local services in action i get below exception 
https://127.0.0.1:7102/soa-infra/resources/default/Bot/login/?userId=101

action code 
 const { data } = await axios.get("https://127.0.0.1:7102/soa-infra/resources/default/Bot/login/?userId="+s1)

Exception :-

STACK TRACE
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at TLSSocket._finishInit (_tls_wrap.js:635:8)

**Comment by James-Quigley** [comment]
Can you share the code/command where you are starting your serve server? Sounds like you're using a self-signed cert, or have provided invalid https certs to serve. If the issue is happening when you're trying to load data from serve that you've provided a self-signed cert to, you will need to load the cert into Axios so it can trust it (https://stackoverflow.com/questions/51363855/how-to-configure-axios-to-use-ssl-certificate)

**Comment by Uranbold** [comment]
How did you resolve this?
