### ISSUE TITLE
Bug: Error: EMFILE: too many open files, open 'C:\xxx\web\build\static\js\main.b1a04325.chunk.js'

### ISSUE THREAD

**Issue by hsluoyz** [zeit/serve#575]
I use `serve` to serve my React app because this docs said so: https://create-react-app.dev/docs/deployment/

React version: 16.12.0
OS: Win 10 x64

## Steps To Reproduce

1. Create a React app.
2. Let a lot of users use it.

## The current behavior

After dozens of minutes of access (~ 20 requests/second), I always encounter such error. It seems that too many people are reading the static files.

```
Microsoft Windows [Version 10.0.17763.914]
(c) 2018 Microsoft Corporation

C:\xxx\web>serve -s build -l 6001

C:\xxx\web>"node"  "C:\Users\Administrator\AppData\Roaming\npm\\node_modules\serve\bin\serve.js" -s build -l 6001

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   Serving!                                      │
   │                                                 │
   │   - Local:            http://localhost:6001     │
   │   - On Your Network:  http://172.17.10.7:6001   │
   │                                                 │
   │   Copied local address to clipboard!            │
   │                                                 │
   └─────────────────────────────────────────────────┘


INFO: Gracefully shutting down. Please wait...
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\xxx\web\build\static\js\main.b1a04325.chunk.js'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:120:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\xxx\\web\\build\\static\\js\\main.b1a04325.chunk.js'
}
```

## The expected behavior

No error.

**Comment by dy** [comment]
Go the same error, with single user.
I use [snowpack](https://ghub.io/snowpack) + [spect](https://ghub.io/spect).
```sh
   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serving!                                        │
   │                                                   │
   │   - Local:            http://localhost:3000       │
   │   - On Your Network:  http://192.168.0.140:3000   │
   │                                                   │
   │   Copied local address to clipboard!              │
   │                                                   │
   └───────────────────────────────────────────────────┘


INFO: Gracefully shutting down. Please wait...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\projects\admin-portal\web_modules\common\ponyfill-74405ca0.js'
Emitted 'error' event at:
    at internal/fs/streams.js:123:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\projects\\admin-portal\\web_modules\\common\\ponyfill-74405ca0.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! admin-portal@1.0.0 start: `serve -l 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-portal@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dfcre\AppData\Roaming\npm-cache\_logs\2020-02-10T18_53_42_469Z-debug.log

```

**Comment by dy** [comment]
Go the same error, with single user.
I use [snowpack](https://ghub.io/snowpack) + [spect](https://ghub.io/spect).
```sh
   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serving!                                        │
   │                                                   │
   │   - Local:            http://localhost:3000       │
   │   - On Your Network:  http://192.168.0.140:3000   │
   │                                                   │
   │   Copied local address to clipboard!              │
   │                                                   │
   └───────────────────────────────────────────────────┘


INFO: Gracefully shutting down. Please wait...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\projects\xxx\web_modules\common\ponyfill-74405ca0.js'
Emitted 'error' event at:
    at internal/fs/streams.js:123:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\projects\\xxx\\web_modules\\common\\ponyfill-74405ca0.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@1.0.0 start: `serve -l 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-portal@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-02-10T18_53_42_469Z-debug.log

```

**Comment by hsluoyz** [comment]
It seems that `serve` is not for production. See this in README:

```
Once it's time to push your site to production, we recommend using ZEIT Now.
```

**Comment by KakakuCZ** [comment]
I use serve for local React application for presentation some graphs base on csv source. Computer with TV is not connected to the internet, so i used serve for local naive server. This app load file called version.txt every 10 seconds and if version change, it will load source csv file (by AJAX - axios).
The big problem is, after some time, serve crashes with error EMFILE too many open files, open 'C:\\*path*\version.txt'. 

This is caused because serve (launched from ajax) opens file but it won't close it.

How I can solve this?

**Comment by hsluoyz** [comment]
Finally I used `waitress`

**Comment by callain** [comment]
Hello, I am not sure this bug should be closed, even if it's not suitable for production.
It should correctly closes files

**Comment by prinze77** [comment]
Same issue happens once a week

` Error: EMFILE: too many open files, open '.../build/static/js/main.9e616f2f.chunk.js'`

**Comment by RReverser** [comment]
For me it happens every ~20 minutes (but then, admittedly, I do make a lot of requests).

**Comment by Juraj-Masiar** [comment]
But why this bug closed?
This happens also when developing locally... simply after some amount of requests the server will simply crash with `Error: EMFILE: too many open files, open` exception.

Anyone here has some workaround maybe?
