### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Bloodyaugust** [zeit/serve#91]
After `npm install -g serve && serve`:
```
const {red} = require('chalk')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

npm version: 3.8.6
running OSX El Capitan v10.11.6

**Comment by leo** [comment]
What's your node version?

**Comment by Bloodyaugust** [comment]
v5.12.0

**Comment by Bloodyaugust** [comment]
Aaaaaand I just saw "requires at least Node LTS". Sorry to bother you all. xP
