### ISSUE TITLE
Syntax error due to async function

### ISSUE THREAD

**Issue by klaemo** [zeit/serve#97]
Hey there,
serve `3.2.6` doesn't start anymore on node `6.9.4` due to what it looks like failed compilation of async functions.

I tried doing a fresh install with `npm rm -g serve && npm i -g serve`, but still seeing the error below.

```
/Users/clemens/.nvm/versions/node/v6.9.4/lib/node_modules/serve/lib/index.js:43
const handler = async (req, res) => {
                      ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/clemens/.nvm/versions/node/v6.9.4/lib/node_modules/serve/node_modules/async-to-gen/register.js:40:5)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/clemens/.nvm/versions/node/v6.9.4/lib/node_modules/serve/bin/serve.js:39:1)
```

edit: sorry, accidentally submitted the issue before writing the actual problem statement :D

**Comment by leo** [comment]
[Fixed!](https://github.com/zeit/now-cli/releases/tag/4.2.2)
